# Generated by Django 5.1.4 on 2025-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='carb_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fat_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='protein_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
