# Generated by Django 5.2.4 on 2025-07-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
