# Generated by Django 5.2.4 on 2025-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_fooddatabase_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddatabase',
            name='fats',
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
