# Generated by Django 5.2.4 on 2025-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_fooddatabase_fats_fooddatabase_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='carb_target',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='daily_calories',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='fat_target',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='protein_target',
        ),
        migrations.AddField(
            model_name='goal',
            name='calorie_goal',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='goal',
            name='carb_goal',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='goal',
            name='fat_goal',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='goal',
            name='protein_goal',
            field=models.FloatField(default=50),
        ),
    ]
