# Generated by Django 5.2.4 on 2025-07-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
